//! RDS AAD Auth PDUs.
//!
//! With RDS AAD Auth ([\[MS-RDPBCGR\] 5.4.5.4]), the client authenticates with a Microsoft Entra ID
//! (formerly Azure AD) token instead of CredSSP. Right after the TLS handshake, the server sends a
//! [`ServerNoncePdu`], the client answers with an [`AuthenticationRequestPdu`] carrying the signed RDP
//! Assertion, and the server reports the outcome in an [`AuthenticationResultPdu`].
//!
//! Each PDU is a UTF-8 encoded JSON object with no length field. The specification does not say how
//! the end of a PDU is found; peers terminate each PDU with a single NUL byte, and so do the
//! encoders here. Use [`RDSAAD_HINT`] to frame incoming PDUs.
//!
//! [\[MS-RDPBCGR\] 5.4.5.4]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/dc43f040-d75d-49a9-90c6-0c9999281136

mod json;

use core::fmt;

use ironrdp_core::{
    Decode, DecodeResult, Encode, EncodeResult, ReadCursor, WriteCursor, ensure_size, invalid_field_err,
    not_enough_bytes_err,
};

use crate::PduHint;

/// Upper bound for the size of a single RDS AAD Auth PDU, NUL terminator included.
///
/// The specification sets no limit. Real PDUs are a few kilobytes at most (the Authentication
/// Request PDU embeds an access token), and without a length field the receiver has to buffer
/// until the terminator shows up, so the bound keeps a misbehaving peer from growing that buffer
/// indefinitely.
pub const MAX_PDU_SIZE: usize = 64 * 1024;

/// Server Nonce PDU.
///
/// Sent by the server right after the TLS handshake. The client embeds the nonce in the RDP
/// Assertion to prove freshness.
///
/// Wire format: `{"ts_nonce":"<nonce_value>"}` followed by a NUL byte.
///
/// Defined in [\[MS-RDPBCGR\] 2.2.18.1].
///
/// [\[MS-RDPBCGR\] 2.2.18.1]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/43e8dd31-7324-4578-bf10-5eb93dd6f4df
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
pub struct ServerNoncePdu {
    /// Opaque nonce generated by the server.
    pub ts_nonce: String,
}

impl ServerNoncePdu {
    const NAME: &'static str = "ServerNoncePdu";

    const FIELD: &'static str = "jsonServerNonce";

    const MEMBER: &'static str = "ts_nonce";
}

impl Encode for ServerNoncePdu {
    fn encode(&self, dst: &mut WriteCursor<'_>) -> EncodeResult<()> {
        ensure_size!(in: dst, size: self.size());

        write_json_message(dst, Self::MEMBER, &|dst| json::write_string(dst, &self.ts_nonce));

        Ok(())
    }

    fn name(&self) -> &'static str {
        Self::NAME
    }

    fn size(&self) -> usize {
        json_message_size(Self::MEMBER, json::string_size(&self.ts_nonce))
    }
}

impl<'de> Decode<'de> for ServerNoncePdu {
    fn decode(src: &mut ReadCursor<'de>) -> DecodeResult<Self> {
        let (start, text) = read_json_message(src, Self::FIELD)?;

        let ts_nonce = match find_member(start, text, Self::FIELD, Self::MEMBER)? {
            json::Value::String(value) => value,
            _ => return Err(invalid_field_err!(Self::FIELD, "ts_nonce is not a string", at: start)),
        };

        Ok(Self { ts_nonce })
    }
}

/// Authentication Request PDU.
///
/// Sent by the client in response to the [`ServerNoncePdu`]. The RDP Assertion is a JWS in Compact
/// Serialization ([\[MS-RDPBCGR\] 2.2.18.2.1]) and effectively functions as a user credential, so the
/// [`Debug`] implementation redacts it.
///
/// Wire format: `{"rdp_assertion":"<rdp_assertion_value>"}` followed by a NUL byte.
///
/// Defined in [\[MS-RDPBCGR\] 2.2.18.2].
///
/// [\[MS-RDPBCGR\] 2.2.18.2]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/411b3a90-d186-4090-890a-6b6eb29cbf4f
/// [\[MS-RDPBCGR\] 2.2.18.2.1]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/ba819b6b-257a-466f-b8e5-f262d78677f7
#[derive(Clone, PartialEq, Eq)]
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
pub struct AuthenticationRequestPdu {
    /// RDP Assertion in JWS Compact Serialization.
    pub rdp_assertion: String,
}

impl AuthenticationRequestPdu {
    const NAME: &'static str = "AuthenticationRequestPdu";

    const FIELD: &'static str = "jsonRdpAssertion";

    const MEMBER: &'static str = "rdp_assertion";
}

impl fmt::Debug for AuthenticationRequestPdu {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("AuthenticationRequestPdu")
            .field("rdp_assertion", &"<redacted>")
            .finish()
    }
}

impl Encode for AuthenticationRequestPdu {
    fn encode(&self, dst: &mut WriteCursor<'_>) -> EncodeResult<()> {
        ensure_size!(in: dst, size: self.size());

        write_json_message(dst, Self::MEMBER, &|dst| json::write_string(dst, &self.rdp_assertion));

        Ok(())
    }

    fn name(&self) -> &'static str {
        Self::NAME
    }

    fn size(&self) -> usize {
        json_message_size(Self::MEMBER, json::string_size(&self.rdp_assertion))
    }
}

impl<'de> Decode<'de> for AuthenticationRequestPdu {
    fn decode(src: &mut ReadCursor<'de>) -> DecodeResult<Self> {
        let (start, text) = read_json_message(src, Self::FIELD)?;

        let rdp_assertion = match find_member(start, text, Self::FIELD, Self::MEMBER)? {
            json::Value::String(value) => value,
            _ => return Err(invalid_field_err!(Self::FIELD, "rdp_assertion is not a string", at: start)),
        };

        Ok(Self { rdp_assertion })
    }
}

/// Authentication Result PDU.
///
/// Sent by the server after validating the RDP Assertion. The connection proceeds only on
/// [`AuthenticationResult::S_OK`].
///
/// Wire format: `{"authentication_result":<error_code>}` followed by a NUL byte.
///
/// The specification shows `error_code` as a JSON string, while deployed servers send a JSON
/// number (FreeRDP only accepts a number). The decoder accepts both, as a number or as a decimal
/// or `0x`-prefixed hexadecimal string, and the encoder emits a number.
///
/// Defined in [\[MS-RDPBCGR\] 2.2.18.3].
///
/// [\[MS-RDPBCGR\] 2.2.18.3]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/fefe9826-e4a0-4763-9c9a-ebacc99a8b5b
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
pub struct AuthenticationResultPdu {
    pub authentication_result: AuthenticationResult,
}

impl AuthenticationResultPdu {
    const NAME: &'static str = "AuthenticationResultPdu";

    const FIELD: &'static str = "jsonAuthResult";

    const MEMBER: &'static str = "authentication_result";
}

impl Encode for AuthenticationResultPdu {
    fn encode(&self, dst: &mut WriteCursor<'_>) -> EncodeResult<()> {
        ensure_size!(in: dst, size: self.size());

        let code = self.authentication_result.0.to_string();
        write_json_message(dst, Self::MEMBER, &|dst| dst.write_slice(code.as_bytes()));

        Ok(())
    }

    fn name(&self) -> &'static str {
        Self::NAME
    }

    fn size(&self) -> usize {
        json_message_size(Self::MEMBER, self.authentication_result.0.to_string().len())
    }
}

impl<'de> Decode<'de> for AuthenticationResultPdu {
    fn decode(src: &mut ReadCursor<'de>) -> DecodeResult<Self> {
        let (start, text) = read_json_message(src, Self::FIELD)?;

        let code = match find_member(start, text, Self::FIELD, Self::MEMBER)? {
            json::Value::Number(number) => parse_decimal_hresult(number),
            json::Value::String(value) => match value.strip_prefix("0x").or_else(|| value.strip_prefix("0X")) {
                Some(hex) => u32::from_str_radix(hex, 16).ok(),
                None => parse_decimal_hresult(&value),
            },
            json::Value::Other => None,
        };

        let code = code.ok_or_else(|| {
            invalid_field_err!(
                Self::FIELD,
                "authentication_result is not a 32-bit HRESULT",
                at: start
            )
        })?;

        Ok(Self {
            authentication_result: AuthenticationResult(code),
        })
    }
}

/// HRESULT reported in the [`AuthenticationResultPdu`] ([\[MS-ERREF\] 2.1]).
///
/// [\[MS-ERREF\] 2.1]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/0642cb2f-2075-4469-918c-4441e69c548a
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
pub struct AuthenticationResult(pub u32);

impl AuthenticationResult {
    /// User authentication and authorization succeeded.
    pub const S_OK: Self = Self(0x0000_0000);
    /// The Authentication Request PDU was invalid.
    pub const SEC_E_INVALID_TOKEN: Self = Self(0x8009_0308);
    /// The user is not authorized to connect to the server.
    pub const E_ACCESSDENIED: Self = Self(0x8007_0005);
    /// The logon attempt failed.
    pub const STATUS_LOGON_FAILURE: Self = Self(0xD000_006D);
    /// No domain controllers are available to service the authentication request.
    pub const STATUS_NO_LOGON_SERVERS: Self = Self(0xD000_005E);
    /// The user account has time restrictions and cannot be used to log on at this time.
    pub const STATUS_INVALID_LOGON_HOURS: Self = Self(0xD000_006F);
    /// The user account cannot be used to log on from the current workstation.
    pub const STATUS_INVALID_WORKSTATION: Self = Self(0xD000_0070);
    /// The user account password has expired.
    pub const STATUS_PASSWORD_EXPIRED: Self = Self(0xD000_0071);
    /// The user account is currently disabled.
    pub const STATUS_ACCOUNT_DISABLED: Self = Self(0xD000_0072);

    pub fn is_success(self) -> bool {
        self == Self::S_OK
    }

    /// Symbolic name for the values listed in [\[MS-RDPBCGR\] 2.2.18.3].
    ///
    /// [\[MS-RDPBCGR\] 2.2.18.3]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/fefe9826-e4a0-4763-9c9a-ebacc99a8b5b
    pub fn name(self) -> Option<&'static str> {
        let name = match self {
            Self::S_OK => "S_OK",
            Self::SEC_E_INVALID_TOKEN => "SEC_E_INVALID_TOKEN",
            Self::E_ACCESSDENIED => "E_ACCESSDENIED",
            Self::STATUS_LOGON_FAILURE => "STATUS_LOGON_FAILURE",
            Self::STATUS_NO_LOGON_SERVERS => "STATUS_NO_LOGON_SERVERS",
            Self::STATUS_INVALID_LOGON_HOURS => "STATUS_INVALID_LOGON_HOURS",
            Self::STATUS_INVALID_WORKSTATION => "STATUS_INVALID_WORKSTATION",
            Self::STATUS_PASSWORD_EXPIRED => "STATUS_PASSWORD_EXPIRED",
            Self::STATUS_ACCOUNT_DISABLED => "STATUS_ACCOUNT_DISABLED",
            _ => return None,
        };

        Some(name)
    }
}

impl fmt::Debug for AuthenticationResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "AuthenticationResult({self})")
    }
}

impl fmt::Display for AuthenticationResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.name() {
            Some(name) => write!(f, "{name} (0x{:08X})", self.0),
            None => write!(f, "0x{:08X}", self.0),
        }
    }
}

/// Frames RDS AAD Auth PDUs: everything up to and including the first NUL byte.
///
/// JSON text never contains a raw NUL (control characters must be escaped inside strings, and
/// UTF-8 continuation bytes are never zero), so the first NUL is the terminator.
#[derive(Clone, Copy, Debug)]
pub struct RdsAadHint;

pub const RDSAAD_HINT: RdsAadHint = RdsAadHint;

impl PduHint for RdsAadHint {
    fn find_size(&self, bytes: &[u8]) -> DecodeResult<Option<(bool, usize)>> {
        let window = bytes.get(..MAX_PDU_SIZE).unwrap_or(bytes);

        match window.iter().position(|&b| b == 0) {
            Some(terminator) => Ok(Some((true, terminator + 1))),
            None if MAX_PDU_SIZE <= bytes.len() => Err(invalid_field_err!(
                "rdsaadPdu",
                "no NUL terminator within the maximum PDU size",
                at: MAX_PDU_SIZE
            )),
            None => Ok(None),
        }
    }
}

fn json_message_size(member: &str, value_size: usize) -> usize {
    1 /* { */ + json::string_size(member) + 1 /* : */ + value_size + 1 /* } */ + 1 /* NUL terminator */
}

/// Writes `{"<member>":<value>}` and the NUL terminator.
///
/// The caller must have checked that `dst` holds at least [`json_message_size`] bytes.
fn write_json_message(dst: &mut WriteCursor<'_>, member: &str, write_value: &dyn Fn(&mut WriteCursor<'_>)) {
    dst.write_u8(b'{');
    json::write_string(dst, member);
    dst.write_u8(b':');
    write_value(dst);
    dst.write_u8(b'}');
    dst.write_u8(0);
}

/// Reads the JSON text of one PDU and its NUL terminator.
///
/// Returns the stream offset of the text alongside the text itself.
fn read_json_message<'de>(src: &mut ReadCursor<'de>, field: &'static str) -> DecodeResult<(usize, &'de str)> {
    let start = src.pos();
    let remaining = src.remaining();
    let window = remaining.get(..MAX_PDU_SIZE).unwrap_or(remaining);

    let Some(text_len) = window.iter().position(|&b| b == 0) else {
        if MAX_PDU_SIZE <= remaining.len() {
            return Err(invalid_field_err!(
                field,
                "no NUL terminator within the maximum PDU size",
                in: src
            ));
        }
        return Err(not_enough_bytes_err!(remaining.len(), remaining.len() + 1, in: src));
    };

    let text = src.read_slice(text_len);
    let _terminator = src.read_u8();

    let text = core::str::from_utf8(text)
        .map_err(|e| invalid_field_err!(field, "invalid UTF-8", at: start + e.valid_up_to()))?;

    Ok((start, text))
}

/// Parses `text` as a JSON object and returns the value of `member`. Other members are ignored.
fn find_member<'a>(
    start: usize,
    text: &'a str,
    field: &'static str,
    member: &'static str,
) -> DecodeResult<json::Value<'a>> {
    let members = json::parse_object(text).map_err(|e| invalid_field_err!(field, e.reason, at: start + e.offset))?;

    members
        .into_iter()
        .find_map(|(name, value)| (name == member).then_some(value))
        .ok_or_else(|| invalid_field_err!(field, "required member is missing", at: start))
}

/// Parses a decimal HRESULT, accepting both the unsigned and the signed (`i32`) rendering.
fn parse_decimal_hresult(text: &str) -> Option<u32> {
    let value: i64 = text.parse().ok()?;

    u32::try_from(value).ok().or_else(|| {
        i32::try_from(value)
            .ok()
            .map(|signed| u32::from_ne_bytes(signed.to_ne_bytes()))
    })
}
